#!/bin/sh
# Guillaume Valadon <guillaume@valadon.net>

# Check if mandatory binaries are installed
detect_binary() {
    command -v "$1" > /dev/null || (echo "Please install the $1 command!" ; return 1)
}

detect_binary "jq" || exit 1
detect_binary "strip" || exit 1

# Get crate metadata
METADATA=$(cargo metadata --format-version 1 2>/dev/null)
if [ "${METADATA}" = "" ]
then
    echo "crate metadata is empty!"
    exit 2
fi

# Retrieve the binary name
METADATA=$(cargo metadata --format-version 1)
BINARY_NAME=$(echo "${METADATA}" |jq -r '.packages[].targets[] | if .kind[] == "bin" then . else empty end |.name')

# Strip the binary if needed
for BINARY in target/*/"${BINARY_NAME}"
do
    if [ "${BINARY}" -nt "${BINARY}.strip_info" ]
    then
        strip "${BINARY}"
        touch "${BINARY}.strip_info"
        echo "${BINARY} stripped"
    fi
done
