on: push

name: CI

jobs:
  build_native:
    name: Build & run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Build & run cargo-strip
        uses: actions-rs/cargo@v1
        with:
          command: run
  build_arm:
    name: Build & run on ARM
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Configure the ARM toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: armv7-unknown-linux-gnueabihf
          override: true
      - name: Build cargo-strip for ARM
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --target armv7-unknown-linux-gnueabihf
      - name: Build & run cargo-strip on the ARM binary
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: -- strip --target armv7-unknown-linux-gnueabihf
