# Trigger the workflow on push or pull request
on: [push, pull_request]

name: CI

jobs:
  build_and_test:
    name: Build & run cargo-strip
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/cargo@v1
        with:
          command: run
